DiamondLightSource/blueapi

src/blueapi/cli/amq.py, src/blueapi/cli/cli.py, src/blueapi/core/__init__.py, src/blueapi/core/bluesky_types.py, src/blueapi/core/context.py, src/blueapi/core/device_lookup.py, src/blueapi/service/app.py, src/blueapi/worker/task.py
`Device` was going to be renamed to `Ability` for Ophyd v2, this no longer looks likely.
=> Rename ability to device

src/blueapi/cli/amq.py, src/blueapi/cli/cli.py, src/blueapi/messaging/__init__.py, src/blueapi/messaging/base.py, src/blueapi/messaging/stomptemplate.py, src/blueapi/service/app.py, tests/messaging/test_stomptemplate.py, tests/messaging/test_utils.py
* Add contextmanager
* Write tests
=> Refactor and tidy messaging interface

src/blueapi/cli/amq.py, src/blueapi/messaging/__init__.py, src/blueapi/messaging/base.py, src/blueapi/messaging/stomptemplate.py, src/blueapi/service/app.py
* Add mechanism for differentiating queues from topics
* Move events to topics
=> Move events to topics

.github/workflows/docs.yml
It will be reenabled when this repository is moved to DiamondLightSource
=> Disable docs CI

src/blueapi/service/app.py
=> Do not require a reply destination for a run plan acknowledgement

.github/workflows/code.yml
Alongside tags, push an image for each branch.
=> Push container images for each branch

.github/workflows/code.yml
This reverts commit a86a7be4a91ccf5a75fbf724d585297f48267603.
=> Revert "Push container images for each branch (#76)"

src/blueapi/cli/cli.py, src/blueapi/config.py, src/blueapi/service/app.py
Changes:
* Make log level configurable in CLI (via command line argument)
* Make log level configurable in service (via config file)
* Set defaults, INFO for service and WARNING for CLI, can be changed later
=> Configurable log level in service and CLI

src/blueapi/core/bluesky_types.py, tests/core/test_context.py
Requires use of a specific function, see #146 for more info
=> Handle future python typing features when checking whether a plan is a plan

docs/user/reference/asyncapi.yaml
=> Set initial API version

catalog-info.yaml
Use names rather than titles, oops
=> Correct API refs

docs/user/reference/openapi.yaml, src/blueapi/cli/cli.py, src/blueapi/service/handler.py, src/blueapi/service/main.py, src/blueapi/worker/reworker.py, src/blueapi/worker/worker.py, tests/conftest.py, tests/service/test_rest_api.py
Required as part of #198 as RunEngine status exposed
=> Allow getting the status from the RunEngineWorker and expose the status to the REST API

catalog-info.yaml
=> Move doc ref to correct section

docs/user/reference/openapi.yaml, src/blueapi/cli/cli.py, src/blueapi/cli/rest.py, src/blueapi/service/main.py, src/blueapi/service/model.py, src/blueapi/worker/reworker.py, src/blueapi/worker/worker.py, tests/service/test_rest_api.py, tests/worker/test_reworker.py
Part of #198 
Additionally exposes clearing pending tasks to the REST API, also a requirement for #198
=> Allow the currently running task to be Stopped or Aborted

helm/blueapi/templates/service.yaml, helm/blueapi/templates/tests/test-ping.yaml, helm/blueapi/values.yaml
- Match Service to Deployment more generically using helper templates
- Ensure test container is configured the same as deployment with absolute paths
=> Minor kubernetes fixes

docs/user/reference/openapi.yaml, src/blueapi/core/bluesky_types.py, src/blueapi/core/context.py, src/blueapi/service/model.py, tests/service/test_rest_api.py, tests/test_cli.py
- Closes #297, #143
- Returns information about call arguments when queried for plans
=> Return more information about plans when queried

src/blueapi/cli/amq.py
* Fix CLI errors when handling different types of event
* Support drawing progress bars in CLI
* Support drawing tables with best effort callback
=> Fix CLI errors on handling events

src/blueapi/service/handler.py, src/blueapi/service/handler_base.py, src/blueapi/service/main.py, tests/service/test_rest_api.py, tests/test_cli.py
Refactor in preparation for #317
=> Extract handler methods to ABC

pyproject.toml
Depend on at least Dodal 1.24.0
=> Add minimum dodal release

codecov.yml
=> coverage upgrade to 85%

tests/service/test_runner.py
Ensure state is initialized after reload.
Add comments for clarity.
=> Enhance environment reload test

.github/workflows/_container.yml
=> 713 quickfix too restrictive semver check - fixing the ref/version parsing

.github/workflows/_container.yml
Simplifies and standardises the passing of the github ref into the Chart.yaml
=> Pass appVersion to helm package command

dev-requirements.txt
=> Update dodal pin to latest

docs/how-to/authenticate.md, src/blueapi/cli/cli.py, src/blueapi/service/authentication.py, tests/unit_tests/test_cli.py
=> Add better error handling for login and docs for authentication

docs/explanations/extension-code.md, docs/explanations/plans.md, docs/explanations/type_validators.md, docs/how-to/edit-live.md, docs/how-to/run-container.md, docs/how-to/write-devices.md, docs/tutorials/installation.md, docs/tutorials/run-bus.md, docs/tutorials/run-with-dev.md
=> Docs update

src/script/start_rabbitmq.sh
=> Update script to use full name

dev-requirements.txt, docs/how-to/write-plans.md, docs/reference/openapi.yaml, pyproject.toml, src/blueapi/cli/format.py, src/blueapi/core/bluesky_types.py, src/blueapi/core/context.py, src/blueapi/service/model.py, src/blueapi/startup/example_devices.py, src/blueapi/startup/example_plans.py, tests/system_tests/devices.json, tests/system_tests/plans.json, tests/system_tests/test_blueapi_system.py, tests/unit_tests/core/test_context.py, tests/unit_tests/service/test_interface.py, tests/unit_tests/service/test_rest_api.py, tests/unit_tests/test_cli.py
=> Update Reference for Movable generics

Dockerfile
=> Set MPLCONFIGDIR environment variable for matplotlib configuration

docs/how-to/edit-live.md, helm/blueapi/templates/configmap.yaml, helm/blueapi/templates/init-configmap.yaml, helm/blueapi/templates/statefulset.yaml, helm/blueapi/values.yaml, tests/unit_tests/test_helm_chart.py
=> Update config map for worker if scratch enabled

pyproject.toml, tests/unit_tests/service/test_openapi.py
=> Add DeepDiff for schema check

tests/unit_tests/test_cli.py
The test appeared to be checking the error status under various error
conditions but those conditions were never being reached due to other
values causing errors before they were raised.
If the intended error was raised, the exit status was also not the one
expected.
=> fix: Fix error handling test so that it tests correct behaviour

docs/how-to/add-plans-and-devices.md
=> docs: Add example of device addition to docs

tests/conftest.py
=> fix: Add assert_all_requests_are_fired False for numtracker mock

.github/workflows/_container.yml
Fixes the publish workflow which was broken by Helm 3.18.0 https://github.com/helm/helm/issues/30873
=> fix(ci): Fix publish workflow for Helm 3.18.0

.copier-answers.yml, .devcontainer/devcontainer.json, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/_release.yml, .github/workflows/_test.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, docs/tutorials/installation.md, pyproject.toml
Accepted all changes other than Python 3.13 as it is not yet supported
by dependencies (scanspec, aioca etc)
See #1014
=> chore: Update copier template

dev-requirements.txt, pyproject.toml
feat: Reference latest version with tracing
=> chore(deps): Update bluesky-stomp

src/blueapi/client/numtracker.py, tests/conftest.py, tests/unit_tests/client/test_numtracker.py
Closes [ACQP_192](https://jira.diamond.ac.uk/browse/ACQP-192)
=> feat: Add rich handling for path/File errors

helm/blueapi/values.yaml, src/blueapi/cli/cli.py, src/blueapi/client/client.py, src/blueapi/client/rest.py, src/blueapi/config.py, src/blueapi/log.py, src/blueapi/service/interface.py, src/blueapi/service/main.py, tests/unit_tests/example_yaml/rest_and_stomp_config.yaml, tests/unit_tests/example_yaml/rest_config.yaml, tests/unit_tests/example_yaml/valid_stomp_config.yaml, tests/unit_tests/service/test_main.py, tests/unit_tests/test_config.py, tests/unit_tests/test_helm_chart.py
=> feat!: Add url to api,stomp and greylog

helm/blueapi/templates/service.yaml, helm/blueapi/templates/statefulset.yaml, helm/blueapi/values.yaml, tests/unit_tests/test_helm_chart.py
=> fix: Allow configuring of service port from chart

Dockerfile
Fixes https://github.com/DiamondLightSource/blueapi/issues/1053
=> fix: Remove python version SHA

docs/reference/openapi.yaml, src/blueapi/service/main.py, src/blueapi/service/openapi.py, tests/unit_tests/service/test_openapi.py, tests/unit_tests/service/test_rest_api.py
=> docs: Add tags to endpoints

helm/blueapi/templates/statefulset.yaml, tests/unit_tests/test_helm_chart.py
It happens to the best of us
To test:
- Check other indentation levels are correct
=> fix: Correct indentation in statefulset

src/blueapi/log.py
=> docs: fix typo

src/blueapi/service/authentication.py
=> feat: Print login URL from IdP

docs/explanations/lifecycle.md, docs/explanations/plans.md, docs/how-to/integrate-with-numtracker.md, docs/how-to/write-devices.md, docs/how-to/write-plans.md, tests/unit_tests/code_examples/count_model.py, tests/unit_tests/code_examples/count_plan.py, tests/unit_tests/code_examples/deferred_plans.py, tests/unit_tests/code_examples/device_module.py, tests/unit_tests/code_examples/invalid_plan_args.py, tests/unit_tests/code_examples/plan_docstrings.py, tests/unit_tests/code_examples/plan_metadata.py, tests/unit_tests/code_examples/plan_module.py, tests/unit_tests/test_example_code.py
=> test(docs): Execute Python snippets in docs

src/blueapi/worker/task_worker.py
=> docs: Add task worker docstrings
