DiamondLightSource/blueapi

- setup.cfg
- tests/core/test_context.py
Mypy 0.991 disallows empty function bodies by default, see https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html
While I have mixed feelings about this change I do find empty bodies useful, for example for dummy functions in tests:
```python
def my_test_function() -> int:
...
def test_something():
assert something_to_do_with(my_test_function.__annotations__)
```
So I have added config to disable it. Empty functions are not widely spread and I could probably also remove them all.
> Explicitly tag empty-bodied functions that are supposed to be empty-bodied

- src/blueapi/cli/amq.py
- src/blueapi/cli/cli.py
- src/blueapi/messaging/stomptemplate.py
- src/blueapi/plans/plans.py
- src/blueapi/worker/event.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
Temporary workaround for #50 
When scanspecs are embedded inside events, they may cause failures when attempting to serialise because their axes are arbitrary `Movable`s. This PR Adds a temporary workaround to ensure the axes are serialized to sensible strings. Long-term solution may be to move to pydantic or similar, requires further investigation. 
This PR also tidies up the structure of task events and doesn't embed the entire task.
> Workaround scanspec serialization issue wtih non-string axes

- pyproject.toml
Related issue: https://github.com/DiamondLightSource/blueapi/issues/57
> Downgrade scanspec because of breaking change

- src/blueapi/messaging/stomptemplate.py
For better interoperability with ActiveMQ and JMS applications, see stomp.py/issues/216
> Disable content length header on stomp messages

- src/blueapi/cli/amq.py
- src/blueapi/service/app.py
The `TaskResponse` model was unused, a raw string was being sent as a response
> Use task response

- src/blueapi/cli/amq.py
- src/blueapi/cli/cli.py
- src/blueapi/cli/updates.py
- src/blueapi/service/app.py
- src/blueapi/startup/example.py
- src/blueapi/startup/simmotor.py
- src/blueapi/worker/__init__.py
- src/blueapi/worker/event.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
- src/blueapi/worker/worker.py
Closes #97 
* Rationalise `WorkerEvent` and `TaskEvent` into new event types: `WorkerEvent`, and `ProgressEvent`. The former is information about the worker and tasks, the latter is information about a running plan.
* Include error messages in `WorkerEvent`
* Make worker catch all exceptions and emit them as events
> Propgate worker errors back to user via message bus

- .github/workflows/code.yml
- src/blueapi/messaging/stomptemplate.py
- src/blueapi/service/app.py
- tests/conftest.py
- tests/messaging/test_stomptemplate.py
Closes #94 
Changes:
* Automatically attempt to reconnect every few seconds (default 10) if stomp connection is lost.
* Allow calling `subscribe()` on a stomp messaging template before calling `connect()`, subscription is deferred internally until after connection. This allows for a nicer, declarative service setup.
* Write system tests for `StompMessagingTemplate`
* Add mechanism to skip system tests if ActiveMQ is not available (e.g. local dev)
* Add activemq as a service in the CI when running tests
> Auto-reconnect to Stomp when connection lost

- codecov.yml
- pyproject.toml
- src/blueapi/core/event.py
- src/blueapi/messaging/base.py
- src/blueapi/messaging/context.py
- src/blueapi/worker/task.py
- src/blueapi/worker/worker.py
- tests/core/test_event.py
- tests/messaging/test_stomptemplate.py
Changes:
* Drop codecov requirement from 85% to 70%, can be revised upward when design is more settled
* Ignore startup directory when running codecov
* Remove ... from abstract methods
* Remove context manager from message template as it was unused
* Cover message listener decorator with test
* Remove unused methods
* Test topics
* Test event streams
> Improve code coverage

- src/blueapi/core/event.py
- src/blueapi/messaging/base.py
- src/blueapi/messaging/context.py
- src/blueapi/messaging/stomptemplate.py
- src/blueapi/service/app.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
- tests/core/test_event.py
- tests/messaging/test_stomptemplate.py
Changes:
* Optionally allow correlation IDs to be propagated through internal events
* Add optional correlation ID to context of received messages, derived from `correlation-id` header in stomp frame
* Add optional correlation ID argument to send message method
* Add tests for the above
* Propagate correlation ID through worker events
* Use correlation ID for plan requests or generate a new one if not present
> Use Correlation ID

- src/blueapi/config.py
- src/blueapi/core/bluesky_types.py
- src/blueapi/core/context.py
- src/blueapi/service/model.py
- src/blueapi/utils/__init__.py
- src/blueapi/utils/base_model.py
- src/blueapi/worker/event.py
- src/blueapi/worker/task.py
Previously, with apischema, the API models were serialized with camel case aliasing. For example, converting a Python field called `foo_bar` to a JSON field called `fooBar` and vice versa. This is to comply with the Google JSON style guide. 
https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format 
This PR adds a custom base model with custom config primarily to preserve this change and also to prevent the ingestion of arbitrary JSON alongside a model's known fields, which apischema also did not allow.
> Make all API models convert to camelCase

- src/blueapi/utils/base_model.py
- src/blueapi/utils/serialization.py
- tests/utils/test_base_model.py
Changes:
* Change default pydantic config so that documents can be deserialized from JSON with camelCase fields but constructed in Python with snake_case fields.
* Add tests to catch if this config ever breaks
* Serialize models with aliases in messaging
> Fix issues with serialization and GDA compatibility

- src/blueapi/utils/type_validator.py
- tests/utils/test_type_validator.py
Several tests broke when using 
```python
from __future__ import annotations
```
Because in the future type annotations will be more lazily. We must use a specific function, `typing.get_type_hints` to properly evaluate them.
This is annoying as we still need to use `signature().parameters` to get the default values, but I could not find a better way.
This PR adds the future import to the tests and invokes the requires function.
> Fix type validators to work with future versions of type hints

- src/blueapi/core/context.py
Previously, BlueskyContext only accepted objects that conformed to the `Readable` or `Flyable` protocols  as devices. This is inherited from the days when all devices conformed to these protocols or their inheritors. Now the protocols no longer have an inheritance heirachy and are mixed and matched through multiple inheritance. The only sensible criteria is whether an object has a `name` property. This opens the door to abuse, storing objects that are definitely not devices, but that may be the price to pay for the required flexibility.
> Make BlueskyContext accept all objects with a name property as devices

- .github/workflows/code.yml
- docs/developer/tutorials/dev-install.rst
- docs/user/tutorials/installation.rst
- pyproject.toml
Fixes: #122 
May also fix #114
> Remove support for Python 3.8

- .devcontainer/Dockerfile
- docs/developer/tutorials/dev-run.rst
- pyproject.toml
- src/blueapi/cli/_deprecated.py
From discussion with @joeshannon, it's probably best if the old CLI command `bluesky` goes away to be replaced with `blueapi` to avoid confusion.
> Rename CLI to blueapi and deprecate old one

- src/blueapi/core/__init__.py
- src/blueapi/core/bluesky_event_loop.py
- src/blueapi/service/app.py
- src/blueapi/worker/multithread.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/worker.py
- tests/worker/test_reworker.py
Changes:
* Change worker API from `run_forever` to `stop` and `start`
* Make `start` run worker in its own thread
> Make worker asynchronous and stoppable

- src/blueapi/worker/reworker.py
- src/blueapi/worker/worker_busy_error.py
- tests/worker/test_reworker.py
made queue have one thing in it. Raising error if attempt to submit while worker is running
> make worker queue have a size of 1

- docs/developer/index.rst
- docs/user/index.rst
* Remove `APIs` sections in toctrees and put them under `Reference`.
* Remove duplicate links in user and developer toctrees
* Add note to developer guide saying it assumes you have read the user guide
> Rationalise docs structure

- src/blueapi/worker/reworker.py
This generates names which are more clearly distinct when looking through logs.
> Use random UUID for StatusView names

- src/blueapi/cli/cli.py
- tests/test_cli.py
fixed a bug in the json parametarization for running plans, so plans can actually be run
> fix json parameterization bug

- pyproject.toml
- tests/service/test_handler.py
- tests/test_cli.py
This was a simple bug; one of the tests in test_cli.py assumed the server isn't running, which means if it is, it fails.
I've mocked out the api call this makes now. So now the tests work with the server running.
> Made tests work with server running

- .github/workflows/asyncapi.yml
- .github/workflows/backstage.yml
- .github/workflows/openapi.yml
modified name of some workflows. Added a backstage catalog-info validator action
> Modify gh actions

- src/blueapi/core/context.py
- tests/core/test_context.py
Passing `None` as the default for a field sets the default to None and
is different to there being no default.
If a default value is given, it is now returned via a default_factory.
This is required to prevent pydantic errors when the default is an ophyd
device.
> Fix handling of default parameters in plans

- src/blueapi/messaging/stomptemplate.py
Previously logging failed due to supply of parameter without a formatting placeholder in the message.
> Fix exception logging in stomptemplate

- src/blueapi/worker/reworker.py
This variable is set to be a UUID so include this in the name to be explicit.
> Rename status name local variable

- catalog-info.yaml
- docs/user/reference/asyncapi.yaml
Update Async API spec to remove so it only describes events all emitted on public.bluesky.event and update catalog info to rename component and API titles according tp scheme agreed with Garry.
> Standardise names and remove publish elements

- src/blueapi/core/event.py
This ensures that if a callback modifies the dictionary there is no 'dictionary changed size during iteration' error.
> Copy subscriptions before iteration

- src/blueapi/worker/reworker.py
- tests/worker/devices.py
- tests/worker/test_reworker.py
For some devices there may be an additional status update broadcast after the on_complete callback. This causes the status to be added back to the dictionary where it will never be removed.
Track which statuses have been completed and check this set when updating to ensure that a completed status is never added back to the snapshot after on_complete is called.
> Track completed statuses (#111)

- src/blueapi/cli/cli.py
- tests/test_cli.py
Instead of an option that is required in every call. If no parameters are passed,
default to empty dict.
> Make run plan parameters an argument

- src/blueapi/service/main.py
Fixes #215 see there for details of the problem. 
In this change:
* Make starting the handler a post-startup task in the FastAPI app
* Remove unnecessary `async` definitions on REST endpoint resolvers
* Store config in the FastAPI app state
> Initialize handler after FastAPI startup

- pyproject.toml
4.6 is causing various issues with protocols and pydantic, see https://github.com/pydantic/pydantic/issues/5821
> Pin typing extensions module to <4.6

- docs/developer/explanations/decisions/0002-no-queues.rst
- src/blueapi/cli/amq.py
- src/blueapi/cli/updates.py
- src/blueapi/core/event.py
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- src/blueapi/worker/__init__.py
- src/blueapi/worker/event.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
- src/blueapi/worker/worker.py
- tests/service/test_rest_api.py
- tests/worker/test_reworker.py
Draft PR with a suggested transaction mode for the worker, transaction mode enables creating of new tasks before they are submitted.
To consider:
* Is the transaction API right?
* Should we allow multiple pending transactions or only one at a time? Currently we lock the transaction mode if one is in progress.
* Can the implementation be simplified? (probably yes)
* Should we still allow non-transaction plan running? (probably not, as it provides a way around the aforementioned transaction lockout)
> Add transaction mode to worker

- catalog-info.yaml
- docs/user/reference/openapi.yaml
- src/blueapi/config.py
- src/blueapi/service/main.py
- tests/service/test_rest_api.py
Rework the existing endpoints to comply with the guidelines:
- Making url object elements plural
- Changing PUT to POST for task creation
- Returning 201 for successful task creation
- Returning Location header of created resource on successful creation
- Adding version header to all endpoint responses
API version is set in app declaration after loading it from REST config object.
Added function to allow easy appending of endpoint specific response headers to defaults
Submit task method refactored to return task id (currently UUID)
> Standardise api

- docs/developer/explanations/decisions/0003-api-case.rst
- src/blueapi/utils/base_model.py
- tests/core/test_context.py
- tests/service/test_rest_api.py
- tests/utils/test_base_model.py
Previously with #132, all config, API parameter and plan model parameter names were converted to camelCase when loaded externally (e.g. from JSON). So 
```python
class TaskResponse(BlueapiBaseModel):
"""
Acknowledgement that a task has started, includes its ID
"""
task_name: str = Field(description="Unique identifier for the task")
```
Would accept the following via the API:
```json
{"taskName": "my task"}
```
and a plan like
```python
def my_plan(foo_bar: str) -> MsgGenerator:
...
```
Would accept:
```json
{"name": "my_plan", "params": {"fooBar": "qwerty"}}
```
This PR removes all aliasing and we accept that there are snake_case models
> Stop models converting to camelCase

- docs/user/reference/openapi.yaml
- src/blueapi/worker/reworker.py
- src/blueapi/worker/worker.py
- tests/service/test_rest_api.py
- tests/worker/test_reworker.py
Changes:
* Replace the `is_error` field on `TrackableTask` with `errors`, a list of strings
*  Include all errors generated while a task is active in its `errors`
* Synchronise `begin_task` so it blocks until the runner thread has set the active task, allows:
```python
worker.begin_task(my_id)
active = worker.get_active_task()
assert active.task_id == my_id
```
> Include errors in current task and synchronise on begin_task

- docs/user/reference/openapi.yaml
This was missed as part of a recent PR. In the future a check will be added to ensure that the committed file matches the current generated file.
> Update OpenAPI Schema to match current state

- tests/test_cli.py
Currently, if pytest is executed with a running server it will fail.
This fixes that - the reason it fails is because it actually makes a HTTP request. Previously, this was being patched, but there have been recent changes to how the CLI makes these requests.
> Make pytest work with server running

- src/blueapi/worker/reworker.py
- tests/worker/test_reworker.py
The worker ensures that `worker.start()` blocks until the worker is ready to execute a task and `worker.stop()` blocks until the worker is no longer able to execute a task. It does so using a group of `threading.Event`s.
There were intermittent issues when events were not being cleaned up correctly, so when the worker was restarted it was not in the correct state. This PR fixes those and cleans up some of the thread control code.
> Fix race condition on worker stop/start

- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
This is a refactor with no changes in behaviour. It was motivated by the fact that `RunEngineWorker` accessed the private function `_lookup_params` in `task.py`. 
* Deprecate `RunPlan` and move its functionality into `Task`
* Add method to `Task` that can optionally be called to cache the parameters, call it when run if not
* Remove instance check on task in worker as it is no longer needed
> Refactor validation

- .github/enabled_plugins
- .github/workflows/code.yml
- docs/developer/how-to/run-tests.rst
- helm/blueapi/values.yaml
- src/blueapi/config.py
- src/blueapi/messaging/base.py
- src/blueapi/messaging/stomptemplate.py
- tests/messaging/test_stomptemplate.py
- Add basic authentication to Stomp connection and Helm chart
- Handle RabbitMQ-style temporary queue behaviour
- Enable CI build against RabbitMQ container
- Add documentation for running against either message bus
> Enable communication with rabbitmq using rabbitmq_stomp plugin

- src/blueapi/messaging/stomptemplate.py
- Add RJMS only header to make deserialising as TextMessage override default deserialising as Bytes: easier to debug and handle.
> Add headers to assist deserialising JMS messages in RMQ

- .devcontainer/Dockerfile
The dockerfile could only built with arguments, either a directory or a wheel to install from. This PR makes the default `.` so that it can be built without any arguments locally. The CI should be unaffected.
> Add defaults such that the Dockerfile can be built locally with no arguments

- docs/user/reference/openapi.yaml
- src/blueapi/service/model.py
- Client unable to deserialise PlanModel without parameter_schema when querying server older than change
- Makes parameter_schema optional to prevent making API incompatible between versions
> Make new fields of PlanModel optional to prevent incompatibility

- docs/user/how-to/add-plans-and-devices.rst
- helm/blueapi/templates/deployment.yaml
- helm/blueapi/values.yaml
- src/blueapi/config.py
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- src/blueapi/service/scratch.py
- tests/service/test_scratch.py
Recent discussion has emphasized the need for an area to checkout Python packages and do dev work against a live instance of blueapi running on Kubernetes. This has previously been done by pushing alpha tags of various packages and continually rebuilding and redeploying the blueapi container, which has become a lengthy and unweildy process.
This PR introduces the "scratch area", a shared directory that can be mounted from the container running on kubernetes, and can install any (pip installable) Python libraries that are cloned into it. In the cases where a dev version of an existing dependency is required (e.g. Dodal), the cloned version will overwrite the existing version installed in the container.
Removing a package and restarting the container works like a factory reset. See …
> Add support for scratch area to automatically add packages when running on Kubernetes

- .devcontainer/Dockerfile
- config/defaults.yaml
- docs/conf.py
- src/blueapi/service/scratch.py
Changes:
- For any modules in scratch that replace exisitnng dependnecies, `importlib.reload()` is called
- Dockerfile now includes a larger Python container with tools needed to pip install
> Reload modules after scratch install

- pyproject.toml
A dependency on a specific branch of dodal was mistakenly merged in #315. This PR reverts that dependency to use the release on PyPi.
> Fix dependency on dodal

- helm/blueapi/templates/deployment.yaml
- helm/blueapi/values.yaml
Changes:
- Add option to helm chart to run on host network, disabled by default
> Add option to helm chart to run on host network

- src/blueapi/core/context.py
- tests/core/test_context.py
Functionality added in https://github.com/DiamondLightSource/blueapi/pull/304 and [being used in hyperion](https://github.com/DiamondLightSource/hyperion/blob/92b23dac5efc1aa78910d2f0f4bd28725a9ec836/src/hyperion/utils/context.py#L81) got removed in https://github.com/DiamondLightSource/blueapi/pull/315/commits/076da45193d3f3460d0481d2bc1a814a6193bcc3 . It doesn't look like there was a clear reason for this removal of functionality so I think it should be reinstated.
>  Allow passing kwargs to make_all_devices for dodal modules (again)

- helm/blueapi/templates/deployment.yaml
- helm/blueapi/values.yaml
- src/blueapi/cli/amq.py
- src/blueapi/cli/cli.py
Chagnes:
* Add CLI command to listen for documents from the message bus and print them to the console
> Add document listener

- src/blueapi/config.py
- src/blueapi/service/handler.py
- src/blueapi/worker/reworker.py
As well as data documents, blueapi produces events when the status objects monitored by the run engine are updated. These events are useful for creating progress bars and similar updates. Unfortunately it seems very easy to unintentionally  make plans/devices produce a very large number of these updates. The handling of all of these results in log spam and high CPU usage. 
We're seeing this now on I22 and have seen similar problems before (see #111). I think the easy way to make debugging easier is to make the status update handling optional and easy to turn off via config. To that end...
Changes:
- Add config option to disable status events
- Make the worker only hook into the run engine if this option is marked as true
> Add configuration option to disable status updates via message bus

- helm/blueapi/templates/deployment.yaml
In a previous PR, I had failed to test that my template for adding a listener actually worked. This is a minor change to fix the issue. I have verified the helm chart installs successfully with this change.
> Minor fix to templating

- helm/blueapi/templates/deployment.yaml
Change helm deployment so we don't spin up a pod in the blueapi deployment that just listens to documents.
At the moment, a deployment using release 0.3.14 fails due to securityContext issues, which when fixed still seem to cause problems. This should be investigated in future.
> Remove listener pod

- src/blueapi/messaging/base.py
- src/blueapi/messaging/stomptemplate.py
- src/blueapi/service/handler.py
- tests/messaging/test_stomptemplate.py
Relates to #220 . This change is to enable blueapi to be shutdown with crtl+c when the activemq drops and it can no longer connect to it.
> Fix shutdown

- docs/user/reference/openapi.yaml
- src/blueapi/cli/rest.py
- src/blueapi/service/handler.py
- src/blueapi/service/handler_base.py
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- src/blueapi/service/subprocess_handler.py
- tests/conftest.py
- tests/service/test_rest_api.py
- tests/service/test_subprocess_handler.py
This approach is possibly not the best design as it results in four definitions of all the functions.
> Run BlueskyContext and Worker in subprocess

- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
- tests/service/test_rest_api.py
Closes #369
The validated and processed parameters from a plan request were being cached inside the `Task` class because they were needed in two separate threads. Unfortunately, with the introduction of the subprocess (#343), pickling was causing issues with the cached object (see #369 for more details).
This PR is the simplest solution: remove the cache and generate the parameters twice. It also adds regression tests for the bug case in #369
> Remove parameter caching inside task class

- docs/user/reference/openapi.yaml
- src/blueapi/cli/cli.py
- src/blueapi/cli/rest.py
- src/blueapi/service/handler.py
- src/blueapi/service/handler_base.py
- src/blueapi/service/main.py
- src/blueapi/service/subprocess_handler.py
- src/blueapi/worker/__init__.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/task.py
- tests/service/test_rest_api.py
- tests/service/test_subprocess_handler.py
- tests/worker/test_reworker.py
quick renaming 36 refs and delete the class
> remove RunPlan class that wraps Task

- src/blueapi/cli/rest.py
- src/blueapi/service/handler.py
- src/blueapi/service/handler_base.py
- src/blueapi/service/main.py
- src/blueapi/service/subprocess_handler.py
- src/blueapi/utils/ophyd_async_connect.py
- src/blueapi/worker/reworker.py
- src/blueapi/worker/worker.py
- tests/service/test_rest_api.py
- tests/service/test_subprocess_handler.py
- tests/utils/test_ophyd_async_connect.py
- tests/worker/test_reworker.py
> 233 pending tasks are not cleared

- pyproject.toml
This is mostly to fix the CI on main before the change to drop python 3.9 is merged and another PR submitted to adapt to latest ophyd-async and dodal changes.
> Pin dodal to previous version

- pyproject.toml
Stomp has changed it's name to `stomp-py` rather than `stomp.py`. This fixes the change
> Update pyproject.toml to new stomp name

- src/blueapi/core/context.py
- tests/core/test_context.py
> Allow context to deal with new style unions and add tests

- pyproject.toml
#384 Moved the coverage settings in pyproject.toml from the pytest settings to the tox command. Some merge conflict kept the settings in both places, which interferes with vscode debugging. This PR removes the redundant settings.
> Fix Coverage Settings

- Dockerfile
This is required for installing python packages at runtime.
It was previously present in the non-slim python container used before but this was accidentally removed with the switch to the copier template.
Fixes #445.
> Install git in runtime container

- helm/blueapi/templates/deployment.yaml
- helm/blueapi/values.yaml
Add new restartOnConfigChange property.
This will cause the deployment to be restarted if the config is changed,
e.g. the set of plans or device modules are updated, when running
helm upgrade.
Use a variation of approach at:
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
Fixes 451.
> Auto restart deployment on config change

- pyproject.toml
Fixes #454
To test:
* Re install `blueapi` dependencies
* `pip list`
* Confirm the installed `starlette`version is `0.27.0`
> Pin sphinx-autobuild to fix starlette clash

- container-startup.sh
Performing an editable install on a shared filesystem scratch area causes cache/version files to be written in the source repository.
With the container's default umask of 0022 the files are not group writable which can lead to frustration when attempting to clean up the scratch area.
Use the DLS "standard" of 0002.
Additionally modify the looping to only pickup directories within the scratch area.
Fixes #478.
> Set umask in container

- src/blueapi/core/context.py
- src/blueapi/startup/example_devices.py
- tests/core/fake_device_module_failing.py
- tests/core/test_context.py
closes https://github.com/DiamondLightSource/blueapi/issues/444
With PR for dodal at https://github.com/DiamondLightSource/dodal/pull/550
> added indexing to handle tuple

- src/blueapi/service/handler.py
- src/blueapi/service/handler_base.py
- src/blueapi/service/main.py
- src/blueapi/service/subprocess_handler.py
- tests/service/test_subprocess_handler.py
It is the worker state rather than the overall state of blueapi.
The "state" name may be used to replace the current "initialized" in order to provide more context about the "environment"
Prerequisite to #514.
> Rename handler "state" to "worker_state"

- src/blueapi/core/context.py
- tests/core/test_context.py
- tests/service/test_rest_api.py
I think this resolves the plan schemas returned from the plans endpoint. Do we
want to include some field in the schema to mark that the field should be a
reference rather than the value itself?
> Correct generated schema for Reference types

- docs/reference/openapi.yaml
- src/blueapi/service/main.py
The method names and docstrings are used in the OppenAPI schema (and therefore Swagger UI).
"update_task" was a bit vague as calling this actually starts the specified task.
> Rename update_task and add some docstrings to REST endpoint methods

- src/blueapi/core/bluesky_types.py
In some cases, possibly when MsgGenerator is defined or imported from
different modules, the types can be equivalent but are not the same
instance. In these cases, the identity check would fail and some plans
would be excluded where they shouldn't be. Using equality checks instead
mean it shouldn't matter where the MsgGenerator type was defined as all
instances should be equal.
> Use equality instead of identity to compare types

- src/blueapi/cli/cli.py
- src/blueapi/cli/format.py
- src/blueapi/startup/example_plans.py
- tests/test_cli.py
Defaults to compact view for now.
Offers
* ~pprint - the current default~
* full - everything in a mostly human readable form
* json - valid json
* compact - most of the information that's likely to be useful for non-machines
Testable by passing the `--output` flag to the `controller` subcommand
```bash
python -m blueapi controller --output json devices
python -m blueapi controller --output json plans
```
> Add formatting options to controller CLI output

- .github/dependabot.yml
Doubly pins some dependencies (in pyproject.toml and in dependabot.yaml) so that these pins will not be automatically removed by dependabot, and dependabot PRs can be consumed without losing the purposeful pinning of known incompatibilities.
See also #273 
TODO: Make issues for the other known problems to track when they are capable of being unpinned
> Configure Dependabot to respect pinned dependencies

- dev-requirements.txt
- docs/reference/asyncapi.yaml
- docs/reference/openapi.yaml
- pyproject.toml
FastAPI and its compatible version of Starlette had a header injection vulnerability, we have committed to move beyond our pinned version and resolve dependency issues in the Java code-gen client
> Unpin dependency on fastapi, click

- pyproject.toml
This was previously available as a transitive dependency from bluesky but has now been removed (bluesky/bluesky#1708).
This is a temporary workaround to make the build work again and may be reverted if the types are made available from bluesky in future.
See #553.
> Add super-state-machine as direct dependency

- helm/blueapi/templates/deployment.yaml
Fixes #458 
Tested on local k3s
> Switch from using helm deployment to stateful set

- docs/reference/openapi.yaml
- src/blueapi/service/model.py
- src/blueapi/service/runner.py
- tests/service/test_rest_api.py
- tests/service/test_runner.py
The code was using `None` or `""` in various places to denote the lack of an error message. `None` is a better semantic fit, so this PR forces the user to pass either `None` or a string with at least 1 character.
> Make environment error message be a non-empty string or None

- src/blueapi/service/interface.py
- src/blueapi/service/main.py
- src/blueapi/service/runner.py
- tests/service/test_interface.py
- tests/service/test_rest_api.py
- tests/service/test_runner.py
> Replace interface singleton class with cached functions

- helm/blueapi/templates/deployment.yaml
Fixes #581 
`extraEnvVars` was being treated as a string in some places and a list in others. This PR makes it a list everywhere, any values files that look like this should be updated to remove the `|`:
```yaml
extraEnvVars: |
- name: BEAMLINE
value: i04
```
> Fix extraEnvVars in helm chart

- src/blueapi/service/main.py
- src/blueapi/service/runner.py
- tests/core/fake_device_module.py
- tests/messaging/test_stomptemplate.py
- tests/service/test_runner.py
> Create very simple RPC so the subprocess loads functions

- src/blueapi/service/runner.py
- tests/core/fake_device_module.py
- tests/service/test_runner.py
> Handle parameterised generics

- src/blueapi/cli/cli.py
- src/blueapi/cli/format.py
- tests/unit_tests/test_cli.py
Listen streams a mix of WorkerEvent, ProgressEvent and DataEvent
instances for anything that the server is doing. This extends the type
handling in the format to each of these types to display the relevant
level of information for each.
Informational messages are changed to be printed to stderr so that the
main stdout output can be piped to an external application (eg jq for
json mode).
> Extend formatting options to listen subcommand

- helm/blueapi/templates/init-configmap.yaml
- helm/blueapi/templates/statefulset.yaml
- helm/blueapi/values.yaml
long branch name due to @DiamondJoseph choice of words in the issue name, but at least it's entertaining
> separate the init config in helm

- helm/blueapi/templates/init-configmap.yaml
- tests/unit_tests/test_config.py
fixes the dodal devices scratch area readout logic
> Init config map quickfix

- .github/workflows/sonarcloud.yml
- sonar-project.properties
> Add sonarcloud workflow

- src/blueapi/config.py
#649 @stan-dot 
For the environment to work, it needed to be in dictionary from so a string to dictionary conversion is needed. This was me playing with it.
You probably already working on it, the cli_value are all none unless you assign them so pydantic keep complaining.
> convert value to dictionary

- .github/workflows/sonarcloud.yml
> The sonarcloud workflow requires an auth key, so will not work with PRs from forks, which we want to support. We will therefore skip that job when the PR is from a fork.
thanks @callumforrester
> Update sonarcloud.yml with the condition for this repo instance

- src/blueapi/config.py
- tests/unit_tests/test_config.py
please validate the directional correctness of the test first. #tdd
> Config setup docs - through tests

- src/blueapi/service/main.py
- src/blueapi/service/openapi.py
- tests/unit_tests/service/test_openapi.py
- tests/unit_tests/service/test_rest_api.py
Defers creation of the FastAPI app, which will allow configuration to be loaded first.
This will allow us to e.g. configure authentication prior to starting the app.
> Do not create FastAPI app until config loaded

- src/blueapi/service/interface.py
Replaces instance of functools.lru_cache with functools.cache.
This is a [faster, more lightweight](https://docs.python.org/3.10/library/functools.html#functools.cache) cache which acts equivalently in this case.
The functions accept no arguments, so can only produce a cache of size one. Due to this, either of the caches are acceptable.
> Replace all instances of functools.lru_cache with functools.cache

- helm/blueapi/templates/configmap.yaml
- helm/blueapi/templates/statefulset.yaml
- helm/blueapi/values.yaml
This handling does not require that string parsing is done on the extraEnvVars, and so resolves the need for them to be a string re: #582
> Extract OTEL parsing to configMap to allow consistent handling of env

- tests/conftest.py
Fixes #736 
Fixes #737 
Due to a small discrepency when updating the copeier template pytest was always running in a mode where it would immediately exit after the first failure. This change reinstates the missing line of code in `conftest.py`.
> Fix pytest break on exception every time

- src/blueapi/service/authentication.py
- tests/unit_tests/service/test_authentication.py
resolve a bug in file saving 
The environment variable `XDG_CONFIG_HOME` contains a directory not a file path. So adding a file name in front of directory path to get a writable location
> Fix auth token saving

- src/blueapi/service/main.py
- src/blueapi/service/runner.py
- tests/system_tests/test_blueapi_system.py
- tests/unit_tests/service/test_rest_api.py
- tests/unit_tests/service/test_runner.py
- tests/unit_tests/test_cli.py
> Properly separate unit tests from system tests WRT subprocess

- .github/workflows/_system_test.yml
- .github/workflows/_test.yml
- .github/workflows/ci.yml
- tests/system_tests/test_blueapi_system.py
> Add CI job to run system tests

- docs/how-to/edit-live.md
- src/blueapi/cli/cli.py
- src/blueapi/cli/scratch.py
- src/blueapi/config.py
- src/blueapi/utils/__init__.py
- src/blueapi/utils/file_permissions.py
- tests/__init__.py
- tests/unit_tests/cli/test_scratch.py
- tests/unit_tests/test_cli.py
- tests/unit_tests/test_config.py
- tests/unit_tests/utils/test_file_permissions.py
> Check for common permissions issues with scratch area

- src/blueapi/worker/task.py
- tests/unit_tests/worker/test_task_worker.py
Let inject work again by using all fields of the built pydantic model including the default ones provided by inject
Fixes #647, #633 
1. Run plan that uses `inject` for default parameters, (eg `blueapi controller run stp_snapshot '{"detectors":["x"]}'` to run the plan from `example_plans`)
2. See that the plan runs correctly with `sample_temperature` and `sample_pressure`. (It may fail at the end of the run with a different error relating to path providers for the detector but this is unrelated).
3. If a plan is created using `inject("<misssing_device_name>")` (as for #633), the plan will not be accepted and blueapi will return `422 Unprocessable Entity`. The detailed error message is generated for this but it's not immediately obvious how to access it. Either way, that should be its own …
> Support inject for default plan arguments again

- docs/reference/openapi.yaml
- src/blueapi/cli/cli.py
- src/blueapi/client/client.py
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- src/blueapi/service/runner.py
- tests/system_tests/test_blueapi_system.py
- tests/unit_tests/client/test_client.py
- tests/unit_tests/client/test_rest.py
- tests/unit_tests/service/test_rest_api.py
- tests/unit_tests/service/test_runner.py
- tests/unit_tests/test_cli.py
> Block until environment reloaded

- tests/unit_tests/test_cli.py
> Hotfix: Add patch instead of creating inaccessible file path in test

- src/blueapi/client/client.py
- src/blueapi/service/runner.py
- tests/unit_tests/service/test_runner.py
Add handler functions to check for Exceptions with message that are None, Empty String or a String that consists only of spaces
Fixes #792
> Acqp-323 prevent blank connection errors in STOMP connections

- src/blueapi/startup/example_devices.py
- tests/system_tests/plans.json
- tests/system_tests/test_blueapi_system.py
This is a workaround (not a fix) for #784, so won't close it. The replacement of `PathProvider` in dodal will eventually provide the proper fix. For now I think we should just pretend to write to a directory with our start-up file, despite the fact that none of the simulated detectors actually write files.
> Add fake `PathProvider` to startup module

- Dockerfile
With this set, the pyc files are created in a mirror directory instead
of the source tree. When running in a shared directory (as is the case
for the scratch area used by bluapi), this prevents files being created
with permissions that prevent other users removing them.
See python docs at
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPYCACHEPREFIX
Fixes #812
1. Deploy and run on p46 with new scratch area
2. Check that there are no `__pycache__` directories created in the scratch area
> Use an external directory for container python cache

- docs/reference/openapi.yaml
- src/blueapi/core/bluesky_types.py
- src/blueapi/core/context.py
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- tests/system_tests/devices.json
- tests/unit_tests/core/fake_device_module.py
- tests/unit_tests/core/test_context.py
- tests/unit_tests/service/test_interface.py
- tests/unit_tests/service/test_rest_api.py
- tests/unit_tests/test_cli.py
- tests/unit_tests/worker/test_task_worker.py
Enum defines a property for `name` and `value`- meaning that according to ducks, any enum class extends `HasName`. Now that we are checking the origin of types, we have started catching this when trying to import plans that take enums as a parameter and possibly even just on devices that have enums as a type arg (e.g. a Movable[ShutterDemand]).
This change makes HasName, HasParent and HasHints on their own no longer sufficient to define that  a class is a Device class.
This was making blueapi try and treat Enum classes as Device classes, and so constructing References which extend them- extending an Enum class is not allowed.
> Prevent Enum classes being treated as Bluesky Protocols

- Dockerfile
- tests/unit_tests/test_helm_chart.py
Possible fix for #559, includes xfailed tests for #646, test helm chart rendering with normal pytests, as suggested by [helm-unittest README](https://github.com/helm-unittest/helm-unittest). By no means exhaustive but a good starting point to build on.
Also include `helm` in the devcontainer.
> Write python tests for helm chart rendering

- docs/reference/openapi.yaml
- src/blueapi/cli/cli.py
- src/blueapi/client/client.py
- src/blueapi/client/rest.py
- src/blueapi/service/main.py
- tests/conftest.py
- tests/unit_tests/service/test_rest_api.py
- tests/unit_tests/test_cli.py
Allows the `/config/oidc` endpoint to return `204 No Content` instead of a OIDCConfig object. This represents to the client that authentication is not configured/not required, allowing the schema of routes to be consistent whether config if configured or not.
This does not resolve the SecuritySchema being present/absent in the schema.
> Always construct auth route

- docs/reference/openapi.yaml
- src/blueapi/service/main.py
- src/blueapi/service/model.py
- src/blueapi/worker/task_worker.py
Prevents 'null' being included as a possible type in the generated
schema which interferes with the generated Java client.
The 'detail' and 'worker' entries on response types were flagged as an
error in the schema when the client was generated.
> Add SkipJsonSchema annotations to optional fields

- src/blueapi/cli/scratch.py
- src/blueapi/config.py
- tests/unit_tests/cli/test_scratch.py
- tests/unit_tests/test_config.py
solves #723 
Added a check in scratch.py at the cloning stage (before even pip install). it is kind of redundant - as I also added a check on the pydantic validation of the config that happens earlier than that. The former might be useful if someone chooses to provide config not-through pydantic models - not sure how that would happen but it's more robust that way. Also added a test for parsing the config.
> add pydantic level validation for blueapi to not be a valid target

- src/blueapi/service/main.py
- tests/unit_tests/service/test_rest_api.py
Ensures that validation errors from within plan parameters are presented
in the same way as those encountered parsing the top level arguments to
the method/endpoint.
Fixes #916
1. Run server with example plans/devices
2. `curl -XPOST localhost:8000/tasks -d '{"name":"stp_snapshot", "params": {"detectors":"not a list"}}' -H 'Content-Type: application/json'`
3. Check that the returned json matches the `HTTPValidationError` spec in the openapi spec
> fix: Return validation error details from submit_task

- docs/tutorials/run-bus.md
- helm/blueapi/values.yaml
- src/blueapi/cli/cli.py
- src/blueapi/client/client.py
- src/blueapi/config.py
- src/blueapi/service/interface.py
- tests/system_tests/test_blueapi_system.py
- tests/unit_tests/example_yaml/rest_and_stomp_config.yaml
- tests/unit_tests/example_yaml/rest_config.yaml
- tests/unit_tests/example_yaml/valid_stomp_config.yaml
- tests/unit_tests/service/test_interface.py
- tests/unit_tests/test_cli.py
- tests/unit_tests/test_config.py
- tests/unit_tests/test_helm_chart.py
Fixes #919 
BREAKING CHANGE: Stomp configuration is now disabled by default in the helm chart. To make blueapi connect to a stomp message broker you have to include`enabled: true` under `worker.stomp` in your `values.yaml` file.
> feat: Enable/disable stomp with a flag in config

- src/blueapi/core/context.py
When running a plan with invalid parameters, the error message would be different depending on whether the required type was generic or not, eg (with #935) 
```
$ uv run --prerelease=allow blueapi -c conf.yaml controller run stp_snapshot '{"detectors": ["xyz"], "pressure": "foo"}'
Error: Incorrect parameters supplied
Invalid value 'xyz' for field detectors.0: Value error, Device xyz is not of type <class 'bluesky.protocols.Readable'>
Invalid value 'foo' for field pressure: Value error, Device foo is not of type bluesky.protocols.Movable[float]
```
where `<class 'bluesky.protocols.Readable'>` and `bluesky.protocols.Movable[float]` should be the same format.
Fixes #934
> fix: Use consistent naming for reference type errors

- dev-requirements.txt
- pyproject.toml
- tests/unit_tests/test_cli.py
click [version 8.2.0](https://github.com/pallets/click/releases/tag/8.2.0) tracks stdout and stderr separately by default, where previously they were unified unless explicitly requested.
We pin to >=8.2.0 (which also drops support for versions of python we do not support either anymore, and so is likely to be using more modern code and practices) and replace the handling in tests that expected to use stderr. There are other tests that check stdout, and we should ensure that we pipe to stdout and stderr correctly.
> fix: Pin click to minimum version with default seperated stdout/stderr

- tests/unit_tests/test_cli.py
The streams are no longer combined (see #946 and click #2523) and
streams can be checked individually in tests.
> chore: Remove outdated comments on cli output streams

- src/blueapi/worker/task_worker.py
- tests/unit_tests/worker/test_task_worker.py
Prevents tasks being started twice.
Fixes #915
> fix: Split tasks into pending and complete

- src/blueapi/cli/cli.py
- tests/unit_tests/test_cli.py
Still doesn't do anything about them but it no longer throws a
stacktrace at the user.
Fixes #894
1. rm ~/.cache/blueapi_cache
2. touch ~/.cache/blueapi_cache
3. blueapi logout
4. Behold lack of stacktrace
> fix: Handle exceptions when logging out

- src/blueapi/core/bluesky_types.py
- src/blueapi/worker/task_worker.py
- tests/unit_tests/client/test_client.py
- tests/unit_tests/test_cli.py
- tests/unit_tests/worker/test_task_worker.py
Including the task_id in the data events (wrapped messages from run engine),
allows clients to filter messages to the specific task that they are
interested.
For instance, in the "submit task => start listening to events => start task"
exchange, it is useful to be able to ignore events received before the start
task fails due to another task running.
> feat!: Add task_id to DataEvents

- CODEOWNERS
Add CODEOWNERS of the DAQ core team, to allow opening the repository up to general editing but require an approving code review from a CODEOWNER, rather than allowing all members of the org to contribute and review simultaneously. This is intended as a living document and is not an end to discussion on codeownership, just a reflection of the current state.
> ci: Add CODEOWNERS

- helm/blueapi/templates/statefulset.yaml
- tests/unit_tests/test_helm_chart.py
Prior to this change, if using an initContainer to setupScratch, the editable install of blueapi that was created by the debug stage of the Dockerfile was overwritten by the non-editable install installed into the venv of the init container when the venv overwrote the main containers.
> fix: Ensure blueapi is editable install when using initContainer

- src/blueapi/core/context.py
- tests/system_tests/plans.json
- tests/unit_tests/core/test_context.py
When a plan is expecting a device name, there is a limited number of
valid devices available to choose from. Making these available in the
schema allows clients to restrict input to valid options only.
Addresses #518
> feat: Enumerate devices in plan schemas

- .copier-answers.yml
- catalog-info.yaml
Fixes #1090
1. I have checked that the core services like numtracker,blueapi,etc are currently under `data-acquisition` and not `core-data-acquisition`
2. Confirm If backstage `component-owner` is correct
> docs: Update `component_owner` for backstage

- src/blueapi/service/main.py
Adjusts logging level for middleware when serving the Kubernetes probes- these endpoints are hit much much more often than any other request and otherwise fill the logs.
> fix: Prevent logs being filled by probes

- src/blueapi/cli/cli.py
Allows the function returned by `@check_connection` to be inspected by type hinting- while `@wraps` already ensured that the actual type hints of the function were passed when e.g. interogated by `main.command`, this allows static type checkers to know that the returned function has the same signature as the wrapped one, in case type checking on e.g. `click.pass_obj` tightens up and expects `Callable[[dict[str, Any], ...], T]`.
Also re-orders the decorators used to a consistent order- the non-mutating exception catching wrapper first, then the argument passing click functions and finally the decorator to install the method as a function to the cli
> docs: add types to check_connection

- src/blueapi/config.py
- src/blueapi/worker/task.py
- tests/unit_tests/core/test_context.py
- tests/unit_tests/service/test_interface.py
- tests/unit_tests/test_config.py
- tests/unit_tests/worker/test_task_worker.py
Removes the instrument session from the config, which is no longer required as of 0.19.0 requiring the instrument_session being passed with the request as of #1062 
This is a breaking change as our Config classes do not allow additional fields. An alternative is to deprecate the field and default it to None, but as this is still pre-1.0.0 I thought it was easier to bundle this change in.
> fix!: Remove instrument_session from config

- docs/how-to/authenticate.md
- docs/reference/openapi.yaml
- helm/blueapi/config_schema.json
- helm/blueapi/values.schema.json
- src/blueapi/config.py
- src/blueapi/service/main.py
- tests/unit_tests/service/test_rest_api.py
- tests/unit_tests/test_config.py
Currently we can logout by going to this https://p46-blueapi.diamond.ac.uk/oauth2/sign_out?rd=https%3A%2F%2Fauthn.diamond.ac.uk%2Frealms%2Fmaster%2Fprotocol%2Fopenid-connect%2Flogout. It will be much simpler to logout by going to https://p46-blueapi.diamond.ac.uk/logout. This is when we have oauth2-proxy enabled for blueapi docs page
> feat: Add logout redirect

- helm/blueapi/README.md
- helm/blueapi/values.schema.json
- helm/blueapi/values.yaml
See https://github.com/losisin/helm-values-schema-json/issues/254 for further context
> fix: Prevent errors when being used as a dependency

- src/blueapi/service/main.py
- tests/unit_tests/service/test_rest_api.py
Currently it is sending the request to the oauth2-proxy but is not redirecting blueapi to the Identity provider so I will give this a try with the  other method in oauth2-proxy docs.
```
[2025/08/27 10:20:01] p46-blueapi.diamond.ac.uk GET blueapi "/logout" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0" 308 0 0.008
10.32.0.21:57828 - 6cc428867cd7ff0b3ddc0faabc4cddcf - b1370833-c4a3-49c2-9a1e-1a69e3854b59 [2025/08/27 10:20:01] p46-blueapi.diamond.ac.uk GET - "/oauth2/sign_out" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0" 302 24 0.000
```
> fix: Use alternative logout url for oauth2

- docs/tutorials/run-bus.md
- src/script/stomp_config.yml
Config was no longer valid and is no longer needed to launch local
rabbitMQ instance.
> docs: Remove example stomp config

- src/blueapi/service/interface.py
- tests/unit_tests/service/test_interface.py
If the headers are only set when they are present but not cleared at the
end of a plan (or when they're absent), a request with no headers
following a request with headers will re-use the previous users
credentials allowing unauthenticated access to running plans.
Setting the headers to an empty map if none are present helps ensure
tokens cannot be used by other users.
Fixes: #1201
> fix: Ensure that numtracker headers are not re-used

- tests/unit_tests/service/test_interface.py
The teardown method is called for all tests in the test_interface module
by the ensure_worker_stopped fixture.
> refactor: Remove redundant teardown from interface tests
